#!/bin/bash
set -exv
WEB_USER=$1
export GIT_USER=$2
ROOT_PRIVATE_FILE=$3
ROOT_PUB_FILE=$4
ADMIN_PRIVATE_FILE=$5
ADMIN_PUB_FILE=$6
GIT_HOME=$7
[[ -n "$WEB_USER" ]] &&
[[ -n "$GIT_USER" ]] &&
[[ -n "$ROOT_PRIVATE_FILE" ]] &&
[[ -n "$ROOT_PUB_FILE" ]] &&
[[ -n "$ADMIN_PRIVATE_FILE" ]] &&
[[ -n "$ADMIN_PUB_FILE" ]] || ( echo "usage: install <root_private_key> <root_public_key> <admin_private_key> <admin_public_key>" && exit 1 )

[[ -f "$ROOT_PRIVATE_FILE" ]] || ( echo "$ROOT_PRIVATE_FILE does not exist" && exit 1 )
export ROOT_PRIVATE_KEY=`cat "$ROOT_PRIVATE_FILE"`
[[ -f "$ROOT_PUB_FILE" ]] || ( echo "$ROOT_PUB_FILE does not exist" && exit 1 )
export ROOT_PUB_KEY=`cat "$ROOT_PUB_FILE"`
[[ -f "$ADMIN_PRIVATE_FILE" ]] || ( echo "$ADMIN_PRIVATE_FILE does not exist" && exit 1 )
export ADMIN_PRIVATE_KEY=`cat "$ADMIN_PRIVATE_FILE"`
[[ -f "$ADMIN_PUB_FILE" ]] || ( echo "$ADMIN_PUB_FILE does not exist" && exit 1 )
export ADMIN_PUB_KEY=`cat "$ADMIN_PUB_FILE"`

echo "installing battleref webserver"

# ! id -u "$WEB_USER" &>/dev/null 2>&1 || ( echo "user $WEB_USER already exists" && exit 1 )

#echo "add $WEB_USER user"
#sudo adduser "$WEB_USER"

if ! id -u "$WEB_USER" &>/dev/null 2>&1
then
	echo "add $WEB_USER user"
	sudo adduser "$WEB_USER"
fi

sudo mkdir -m 0755 -p /opt/git

cd /opt/git
if [[ -e /opt/git/battleref.git ]]
then
	sudo rm -rf /opt/git/battleref.git
fi
sudo git clone --mirror "$GIT_HOME/.git"

sudo cp -n "$GIT_HOME/post-receive" "/opt/git/battleref.git/hooks/"
sudo chown -R "$WEB_USER:$WEB_USER" "/opt/git/"

export AUTH_KEYS=`cat ~/.ssh/authorized_keys`
sudo -E su "$WEB_USER" <<'EOF'
	set -exv
	cd 
	mkdir -m 0700 -p .ssh
	echo "$ROOT_PRIVATE_KEY" > .ssh/root
	echo "$ROOT_PUB_KEY" > .ssh/root.pub
	echo "$ADMIN_PRIVATE_KEY" > .ssh/admin
	echo "$ADMIN_PUB_KEY" > .ssh/admin.pub
	chmod 0700 ./.ssh/*
	echo <<'EOM'
Host git.local
    HostName localhost
    User "$GIT_USER"
    IdentityFile ~/.ssh/admin

Host git-root.local
    HostName localhost
    User "$GIT_USER"
    IdentityFile ~/.ssh/root
EOM
	mkdir -p ~/.battleref
	echo "$AUTH_KEYS" > .ssh/authorized_keys
	chmod 0644 ".ssh/authorized_keys"

	mkdir -p golib
	export GOPATH=~/golib
	go get "github.com/mattn/go-sqlite3"
	go install "github.com/mattn/go-sqlite3"

EOF



