#!/bin/bash
set -ex
REPOA=$1
HASHA=$2
REPOB=$3
HASHB=$4
MAP=$5
GIT_SERVER=$6
BATTLECODE=$7

echo "run match $REPOA vs $REPOB"

TEMPDIR=`mktemp -d -t "$NAME"`
cp -r sandbox "$BATTLECODE" "$TEMPDIR"

cd "$TEMPDIR"
mkdir -p "teams"
git clone "git@$GIT_SERVER:$REPOA" "teams/$REPOA"
cd "teams/$REPOA"
git checkout "$HASHA"
cd "$TEMPDIR"

git clone "git@$GIT_SERVER:$REPOB" "teams/$REPOB" 
cd "teams/$REPOB"
git checkout "$HASHB"
cd "$TEMPDIR"

cp bc.conf.template bc.conf

echo "# Headless settings" >> bc.conf
echo "bc.game.maps=$MAP" >> bc.conf
echo "bc.game.team-a=$REPOA" >> bc.conf
echo "bc.game.team-b=$REPOB" >> bc.conf
echo "bc.game.save-file=match.rms" >> bc.conf

ant file -Dc=bc.conf # > output.log 2> error.log

rm -rf "$TEMPDIR"
