#!/bin/bash
HOST=http://localhost:4001
set -ex
curl "$HOST/map/submit?name=maze"

curl "$HOST/register?name=glen&public_key=1&silent=1"
curl "$HOST/register?name=rupert&public_key=2&silent=1"
curl "$HOST/register?name=tomos&public_key=3&silent=1"

curl "$HOST/revision/submit?repo=glen&commit=aaaaa&silent=1"
curl "$HOST/revision/submit?repo=glen&commit=aaaab&silent=1"
curl "$HOST/revision/submit?repo=glen&commit=aaaac&silent=1"

curl "$HOST/revision/submit?repo=rupert&commit=bbbba&silent=1"
curl "$HOST/revision/submit?repo=rupert&commit=bbbbb&silent=1"
curl "$HOST/revision/submit?repo=rupert&commit=bbbbc&silent=1"

curl "$HOST/revision/submit?repo=tomos&commit=ccccca&silent=1"
curl "$HOST/revision/submit?repo=tomos&commit=cccccb&silent=1"
curl "$HOST/revision/submit?repo=tomos&commit=cccccc&silent=1"

