#!/bin/bash
NAME=$1
BRANCH=$2
GIT_HOST=$3
# set -ex
rm -rf "$NAME.git"
git clone --bare "git@$GIT_HOST:$NAME.git"
cd "$NAME.git"
git log "$BRANCH" || EXIT=$?
cd ..
rm -rf $NAME.git
[[ "$EXIT" -eq "0" ]]