#!/bin/bash

# install app via ssh
# usage: install api.akusete.com github.com/GlenKelley/battlecode

export HOST=api.akusete.com
export REPO=github.com/GlenKelley/battleref

set -exv
[[ -n "$HOST" ]] &&
[[ -n "$REPO" ]] || ( "usage: install hostname gitrepo" && exit 1 )

ssh -E "$REPO"<<'EOF'
set -ex
DIR=$(mktemp -d -t battleref_install)
git clone "$REPO" "$DIR"
export GIT_REPO="$DIR"
R="$DIR/scripts/install_battleref"
rm -rf "$DIR"
EOF

