#!/bin/bash
set -ex

ROOT_KEY=~/.ssh/root
ADMIN_KEY=~/.ssh/admin

if [[ ! -f "$ROOT_KEY" ]]
then 
	echo "creating root key"
	ssh-keygen -f "$ROOT_KEY" -P "" -C "battleref webserver key"
fi

if [[ ! -f "$ADMIN_KEY" ]]
then 
	echo "creating admin key"
	ssh-keygen -f "$ADMIN_KEY" -P "" -C "battleref gitolite admin key"
fi

GIT_USER=git
WEB_USER=webserver

if ! which git
then
	echo "installing git"
	sudo yum install git
fi

if ! which gcc
then
	echo "installing gcc"
	sudo yum install gcc
fi

if ! perl -e 'user Data::Dumper'
then
	echo "installing perl module Data::Dumper"
	sudo yum install perl-Data-Dumper
fi

if ! which go
then
	echo "installing go"
	sudo yum install go
fi

echo "installing libcurl"
sudo yum install curl libcurl

GIT_ROOT=`git rev-parse --show-toplevel`
[[ -n "$GIT_ROOT" ]] || ( echo "must run in repository" && exit 1 )

"$GIT_ROOT/scripts/install_gitolite" "$GIT_USER" "$ROOT_KEY.pub" "$ADMIN_KEY.pub"
"$GIT_ROOT/scripts/install_webserver" "$WEB_USER" "$GIT_USER" "$ROOT_KEY" "$ROOT_KEY.pub" "$ADMIN_KEY" "$ADMIN_KEY.pub" "$GIT_ROOT"

