#!/bin/bash
NAME=$1
BRANCH=$2
GIT_HOST=$3
# set -ex
TEMPDIR=`mktemp -d -t "$NAME"`
# rm -rf "$NAME.git"
git clone --bare "git@$GIT_HOST:$NAME.git" "$TEMPDIR"
cd "$TEMPDIR"
EXIT=git log "$BRANCH"
cd ..
rm -rf "$TEMPDIR"
[[ "$EXIT" -eq "0" ]]