#!/bin/bash
NAME=$1
GIT_HOST=$2
DEFAULT_PLAYER=$3
set -ex
TEMPDIR=`mktemp -d -t "$NAME"`
git init "$TEMPDIR"
sed "1s/package defaultplayer;/package $NAME;/" "$DEFAULT_PLAYER" > "$TEMPDIR"/RobotPlayer.java
cd "$TEMPDIR"
git commit -m "default player" RobotPlayer.java
git push --mirror "git@$GIT_HOST:$NAME.git"
rm -rf "$TEMPDIR"